name: ci

on:
  push:
    branches:
      - main

jobs:
  deploy-openai-infrastructure-to-dev:
    uses: ./.github/workflows/openai-infrastructure.yaml
    with:
      environment: dev
    secrets: inherit

  deploy-main-infrastructure-to-dev:
    needs: deploy-openai-infrastructure-to-dev
    uses: ./.github/workflows/main-infrastructure.yaml
    with:
      environment: dev
    secrets: inherit
