name: ci

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastracture-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Variables
        uses: ./.github/actions/setup-environment-variables
        with:
          environment: dev

      - name: Check
        run: echo ${{ env.AZ_TERRAFORM_BACKEND_RESOURCEGROUP }}
